# Generated by Django 4.1.7 on 2023-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25)),
                ("email", models.CharField(max_length=70)),
                ("senha", models.CharField(max_length=15)),
                ("tel", models.CharField(blank=True, max_length=11)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("about", models.TextField(blank=True, max_length=255)),
                ("photo", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
