# Generated by Django 4.1.7 on 2023-03-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutores", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor",
            old_name="city",
            new_name="cidade",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="photo",
            new_name="foto",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="about",
            new_name="sobre",
        ),
        migrations.RenameField(
            model_name="tutor",
            old_name="tel",
            new_name="telefone",
        ),
    ]
