# Generated by Django 4.1.7 on 2023-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutores", "0002_rename_city_tutor_cidade_rename_photo_tutor_foto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="senha",
            field=models.CharField(max_length=100),
        ),
    ]
