# Generated by Django 4.1.7 on 2023-03-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutores", "0003_alter_tutor_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
