# Generated by Django 4.1.7 on 2023-03-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutores", "0004_alter_tutor_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="email",
            field=models.EmailField(max_length=70),
        ),
    ]
