# Generated by Django 4.1.7 on 2023-03-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutores", "0005_alter_tutor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos/%Y/%m/%d/"),
        ),
    ]
